### ISSUE TITLE
مشکل اجرا گرافیک در ویندوز

### ISSUE THREAD

**Issue by Matinpirvali** [Matinpirvali/tmr_p#3]
App need Python3
Pelease install requirements : with "pip install -r GUI/lib/requirements.txt"

System Guard Verifred os: Windows
Traceback (most recent call last):
  File "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main (6)\tmr_p-main\GUI\mainGUI.py", line 13, in <module>
    run_w()
  File "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main (6)\tmr_p-main\GUI\lib\win.py", line 20, in run_w
    set_default_color_theme("dark-blue")
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'set_default_color_theme' is not defined

**Comment by BDadmehr0** [comment]
ایا پیش نیاز های برنامه رو نصب کردید ؟
اگر نه در پروژه توضیح داده شده

**Comment by BDadmehr0** [comment]
نصب خودکار نوشته شد دوباره اجرا کنید

**Comment by Matinpirvali** [comment]
C:\Users\NP\AppData\Local\Programs\Python\Python311\python.exe "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main (6)\tmr_p-main\GUI\mainGUI.py" 
  File "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main (6)\tmr_p-main\GUI\mainGUI.py", line 6
    def installion()
                    ^
SyntaxError: expected ':'

**Comment by BDadmehr0** [comment]
این مشکل سینتکس هست، دوباره امتحان کنید

**Comment by Matinpirvali** [comment]
مشکل کد بود رفع کردم اینو ولی باز مشکل پیش اومد

**Comment by Matinpirvali** [comment]
C:\Users\NP\AppData\Local\Programs\Python\Python311\python.exe C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main\GUI\mainGUI.py 
App need Python3
Pelease install requirements : with "pip install -r GUI/lib/requirements.txt"

App need Python3
Pelease install requirements : with "pip install -r GUI/lib/requirements.txt"

System Guard Verifred os: Windows
Traceback (most recent call last):
  File "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main\GUI\mainGUI.py", line 23, in <module>
    run_w()
  File "C:\Users\NP\PycharmProjects\pythonProject8\tmr_p-main\GUI\lib\win.py", line 20, in run_w
    set_default_color_theme("dark-blue")
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'set_default_color_theme' is not defined

**Comment by BDadmehr0** [comment]
دوباره تست کن

**Comment by BDadmehr0** [comment]
من الان روی یک سیستم ویندوزی تست کردم مشکلی نداشت
